import type {
  UserProfile,
  FamilyCaregiver,
  Appointment,
  Medication,
  MedDoseHistory,
  MedFile,
  TutorialCategory,
  AuditLog,
  NotificationItem,
} from './types';

export const patientUser: UserProfile = {
  id: 'usr-001',
  name: 'María Rodríguez',
  firstName: 'María',
  idNumber: '1.024.567.890',
  birthDate: '15 de marzo de 1988',
  address: 'Calle 45 # 23-67, Bogotá D.C.',
  phone: '+57 320 456 7890',
  email: 'maria.rodriguez@gmail.com',
  eps: 'Sanitas EPS',
  ips: 'Centro Médico El Bosque',
  bloodType: 'O+',
  allergies: ['Penicilina (Anafilaxia leve)', 'Aspirina / AINEs', 'Látex'],
  conditions: [
    'Hipertensión arterial esencial (I10 - Controlada)',
    'Diabetes mellitus tipo 2 (E11.9 - En manejo farmacológico)',
  ],
  surgeries: ['Apendicectomía por laparoscopia (2018)', 'Cesárea electiva (2015)'],
  emergencyContact: {
    name: 'Carlos Rodríguez',
    relation: 'Hermano (Cuidador principal)',
    phone: '+57 310 234 5678',
  },
  twoFactorEnabled: true,
  dataConsentGranted: true,
  dataConsentDate: '2026-08-28 09:15:00',
};

export const familyCaregivers: FamilyCaregiver[] = [
  {
    id: 'fam-001',
    name: 'Carlos Rodríguez',
    relation: 'Hermano / Cuidador Principal',
    phone: '+57 310 234 5678',
    email: 'carlos.rodriguez@gmail.com',
    status: 'active',
    permissions: {
      viewAgenda: true,
      viewMeds: true,
      viewHistory: true,
      receiveAlerts: true,
    },
  },
  {
    id: 'fam-002',
    name: 'Lucía Ospina',
    relation: 'Hija mayor',
    phone: '+57 315 876 5432',
    email: 'lucia.ospina@gmail.com',
    status: 'pending',
    permissions: {
      viewAgenda: true,
      viewMeds: false,
      viewHistory: false,
      receiveAlerts: true,
    },
  },
];

export const appointments: Appointment[] = [
  {
    id: 'apt-001',
    patientId: 'usr-001',
    date: '2026-09-04',
    time: '09:30',
    specialty: 'Medicina General',
    doctor: 'Dr. Andrés Morales',
    center: 'Centro Médico El Bosque - Consultorio 304',
    status: 'pending',
    notes: 'Control semestral de presión arterial y revisión de glucemia.',
  },
  {
    id: 'apt-002',
    patientId: 'usr-001',
    date: '2026-09-10',
    time: '14:00',
    specialty: 'Cardiología',
    doctor: 'Dra. Claudia Vega',
    center: 'Clínica del Norte - Piso 2',
    status: 'pending',
    notes: 'Revisión de electrocardiograma de control y ajuste posológico.',
  },
  {
    id: 'apt-003',
    patientId: 'usr-001',
    date: '2026-09-15',
    time: '08:00',
    specialty: 'Laboratorio Clínico',
    doctor: 'Tec. Roberto Suárez',
    center: 'Centro Médico El Bosque - Toma de Muestras',
    status: 'pending',
    notes: 'Perfil lipídico, Hemoglobina glicosilada (HbA1c) en ayunas (10h).',
  },
  {
    id: 'apt-004',
    patientId: 'usr-001',
    date: '2026-08-28',
    time: '10:00',
    specialty: 'Laboratorio Clínico',
    doctor: 'Tec. Roberto Suárez',
    center: 'Centro Médico El Bosque',
    status: 'done',
    notes: 'Hemograma completo y creatinina realizados satisfactoriamente.',
  },
  {
    id: 'apt-005',
    patientId: 'usr-001',
    date: '2026-08-20',
    time: '11:30',
    specialty: 'Oftalmología',
    doctor: 'Dra. Sofía Gómez',
    center: 'Instituto Oftalmológico Nacional',
    status: 'cancelled',
    notes: 'Cancelada por el paciente por cruce de horario laboral. Pendiente reprogramar.',
  },
];

export const initialMedications: Medication[] = [
  {
    id: 'med-001',
    patientId: 'usr-001',
    name: 'Enalapril',
    dose: '10 mg',
    frequency: 'Cada 12 horas (08:00 / 20:00)',
    timeOfDay: ['08:00', '20:00'],
    durationDays: 90,
    daysElapsed: 76,
    takenToday: 'taken',
    lastTakenTime: '08:05',
    prescribedBy: 'Dr. Andrés Morales (Medicina General)',
  },
  {
    id: 'med-002',
    patientId: 'usr-001',
    name: 'Metformina',
    dose: '500 mg',
    frequency: 'Cada 8 horas con las comidas',
    timeOfDay: ['07:30', '13:00', '19:30'],
    durationDays: 30,
    daysElapsed: 26,
    takenToday: 'none',
    prescribedBy: 'Dr. Andrés Morales (Medicina General)',
  },
  {
    id: 'med-003',
    patientId: 'usr-001',
    name: 'Omeprazol',
    dose: '20 mg',
    frequency: 'Una vez al día (En ayunas)',
    timeOfDay: ['07:00'],
    durationDays: 14,
    daysElapsed: 13,
    takenToday: 'none',
    prescribedBy: 'Dra. Claudia Vega (Cardiología)',
  },
  {
    id: 'med-004',
    patientId: 'usr-001',
    name: 'Atorvastatina',
    dose: '20 mg',
    frequency: 'Una vez al día (Noche)',
    timeOfDay: ['21:00'],
    durationDays: 60,
    daysElapsed: 15,
    takenToday: 'none',
    prescribedBy: 'Dra. Claudia Vega (Cardiología)',
  },
];

export const initialDoseHistory: MedDoseHistory[] = [
  {
    id: 'dh-001',
    medicationId: 'med-001',
    medicationName: 'Enalapril 10 mg',
    date: '2026-09-02',
    time: '08:05',
    status: 'taken',
  },
  {
    id: 'dh-002',
    medicationId: 'med-002',
    medicationName: 'Metformina 500 mg',
    date: '2026-09-01',
    time: '19:40',
    status: 'taken',
  },
  {
    id: 'dh-003',
    medicationId: 'med-003',
    medicationName: 'Omeprazol 20 mg',
    date: '2026-09-01',
    time: '07:15',
    status: 'taken',
  },
  {
    id: 'dh-004',
    medicationId: 'med-001',
    medicationName: 'Enalapril 10 mg',
    date: '2026-08-31',
    time: '20:00',
    status: 'skipped',
  },
];

export const medFiles: MedFile[] = [
  {
    id: 'doc-001',
    patientId: 'usr-001',
    name: 'Resultado Hemograma Completo y Glucemia',
    type: 'PDF',
    category: 'Laboratorio',
    date: '2026-08-28',
    size: '1.2 MB',
    encrypted: true,
    institution: 'Laboratorios El Bosque',
  },
  {
    id: 'doc-002',
    patientId: 'usr-001',
    name: 'Radiografía de Tórax AP y Lateral',
    type: 'Radiografía',
    category: 'Imagenología',
    date: '2026-07-15',
    size: '4.8 MB',
    encrypted: true,
    institution: 'Clínica del Norte - Imágenes Diagnósticas',
  },
  {
    id: 'doc-003',
    patientId: 'usr-001',
    name: 'Electrocardiograma de Reposo 12 Derivaciones',
    type: 'PDF',
    category: 'Diagnóstico',
    date: '2026-06-30',
    size: '850 KB',
    encrypted: true,
    institution: 'Clínica del Norte - Cardiología',
  },
  {
    id: 'doc-004',
    patientId: 'usr-001',
    name: 'Ecografía Abdominal Total',
    type: 'Imagen',
    category: 'Imagenología',
    date: '2026-05-12',
    size: '3.4 MB',
    encrypted: true,
    institution: 'Centro Médico Diagnóstico',
  },
];

export const tutorials: TutorialCategory[] = [
  {
    id: 'tut-001',
    title: 'Agendar Cita Médica Online',
    emoji: '📅',
    description: 'Solicita tus citas de medicina general y especialistas desde el portal de tu EPS sin hacer filas.',
    color: '#EBF3FD',
    entityName: 'Superintendencia Nacional de Salud',
    officialUrl: 'https://www.supersalud.gov.co',
    verified: true,
    steps: [
      {
        title: 'Ingresa a la aplicación o portal web de tu EPS',
        description: 'Accede al sitio web oficial de tu EPS (Sanitas, Sura, Famisanar, Nueva EPS) o descarga su aplicación móvil oficial desde Google Play o App Store.',
      },
      {
        title: 'Inicia sesión con tu número de identificación',
        description: 'Digita tu cédula de ciudadanía o tarjeta de identidad junto con tu clave de acceso seguro personal.',
      },
      {
        title: 'Selecciona "Citas Médicas" y elige la especialidad',
        description: 'Ubica en el menú principal la opción "Agendamiento de Citas". Elige la especialidad solicitada (Medicina General, Odontología, etc.).',
      },
      {
        title: 'Selecciona sede IPS más cercana, fecha y horario',
        description: 'Filtra por tu ciudad o localidad preferida. El sistema te mostrará los médicos y horarios disponibles en tiempo real.',
      },
      {
        title: 'Confirma la cita y descarga tu comprobante',
        description: 'Revisa los datos de la cita y haz clic en confirmar. Recibirás un mensaje SMS y correo con el código de confirmación de asistencia.',
      },
    ],
  },
  {
    id: 'tut-002',
    title: 'Consultar y Descargar Resultados de Laboratorio',
    emoji: '🔬',
    description: 'Accede a tus resultados de laboratorio clínico, exámenes de sangre e imágenes diagnósticas.',
    color: '#ECFDF5',
    entityName: 'Ministerio de Salud y Protección Social',
    officialUrl: 'https://www.minsalud.gov.co',
    verified: true,
    steps: [
      {
        title: 'Entra al portal de resultados de tu IPS o Laboratorio',
        description: 'Visita el sitio web del laboratorio clínico donde te tomaron las muestras biológicas o exámenes.',
      },
      {
        title: 'Autentícate con tu orden médica y documento',
        description: 'Digita el número de orden o radicado entregado el día del examen junto a tu documento de identidad.',
      },
      {
        title: 'Descarga el informe médico oficial en formato PDF',
        description: 'Verifica que el archivo incluya la firma digital del bacteriólogo o patólogo responsable.',
      },
      {
        title: 'Adjúntalo en tu expediente de GuiaSalud',
        description: 'Carga el archivo PDF en el módulo "Historia Clínica" de GuiaSalud para mantenerlo centralizado y cifrado.',
      },
    ],
  },
  {
    id: 'tut-003',
    title: 'Descargar Certificados de Afiliación EPS',
    emoji: '📄',
    description: 'Genera tu certificado de afiliación vigente con validación de código de barras y firma digital.',
    color: '#FFEDD5',
    entityName: 'ADRES - Administradora de los Recursos del SGSSS',
    officialUrl: 'https://www.adres.gov.co/consulte-su-eps',
    verified: true,
    steps: [
      {
        title: 'Ingresa al portal de consulta de ADRES o de tu EPS',
        description: 'Puedes consultar el estado de afiliación oficial en la BDUA de ADRES o directamente en la página de tu EPS.',
      },
      {
        title: 'Ingresa tipo y número de documento',
        description: 'Selecciona tu tipo de identificación (CC, TI, CE, PPT) e ingresa el número.',
      },
      {
        title: 'Genera el certificado de afiliación',
        description: 'Elige la opción "Generar Certificado de Afiliación", donde constará tu estado (Activo), régimen (Contributivo/Subsidiado) y beneficiarios.',
      },
      {
        title: 'Descarga e imprime con validez legal',
        description: 'El documento PDF generado cuenta con código QR de verificación para presentar en trámites laborales o notariales.',
      },
    ],
  },
  {
    id: 'tut-004',
    title: 'Solicitar y Radicar Autorizaciones Médicas',
    emoji: '✅',
    description: 'Radica órdenes de procedimientos, medicamentos especiales e interconsultas especializadas.',
    color: '#FEF3C7',
    entityName: 'Superintendencia Nacional de Salud',
    officialUrl: 'https://www.supersalud.gov.co',
    verified: true,
    steps: [
      {
        title: 'Verifica la orden médica y el código CIE-10 / CUPS',
        description: 'Asegúrate de que la fórmula emitida por tu médico tratante tenga diagnóstico claro y vigencia menor a 30 días.',
      },
      {
        title: 'Radica en la oficina virtual de tu EPS',
        description: 'Ingresa a la sección "Autorizaciones en Línea", adjunta la foto o escaneo nítido de la orden médica y resumen de historia clínica.',
      },
      {
        title: 'Conserva el número de radicado',
        description: 'El sistema te asignará un código único para seguimiento del trámite en tiempo real.',
      },
      {
        title: 'Respuesta dentro del término legal',
        description: 'La EPS debe responder en máximo 5 días hábiles para servicios electivos o 24 horas para servicios prioritarios según Circular 008 de la Supersalud.',
      },
    ],
  },
  {
    id: 'tut-005',
    title: 'Consulta de Clasificación Sisbén IV',
    emoji: '📊',
    description: 'Averigua tu grupo Sisbén (A, B, C, D) para acceder al Régimen Subsidiado de Salud.',
    color: '#F3E8FF',
    entityName: 'Departamento Nacional de Planeación (DNP)',
    officialUrl: 'https://www.sisben.gov.co',
    verified: true,
    steps: [
      {
        title: 'Ingresa a la página oficial de Sisbén IV',
        description: 'Dirígete a www.sisben.gov.co y selecciona el botón "Consulta tu grupo Sisbén".',
      },
      {
        title: 'Diligencia tu tipo y número de documento',
        description: 'Ingresa tus datos y resuelve el captcha de validación de seguridad.',
      },
      {
        title: 'Revisa tu ficha de caracterización socioeconómica',
        description: 'Podrás ver tu grupo asignado (Grupo A: Pobreza extrema, Grupo B: Pobreza moderada, Grupo C: Vulnerabilidad, Grupo D: No pobre).',
      },
      {
        title: 'Solicita afiliación al régimen subsidiado de ser aplicable',
        description: 'Si estás en grupos A o B y no tienes capacidad de pago contributivo, tienes derecho a cobertura médica 100% gratuita por el Estado.',
      },
    ],
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-09-02 18:25:10',
    userEmail: 'maria.rodriguez@gmail.com',
    userRole: 'patient',
    action: 'LOGIN_2FA_SUCCESS',
    module: 'Autenticación',
    details: 'Inicio de sesión exitoso con Doble Factor (2FA - SMS token validado)',
    ipAddress: '190.84.112.45',
    status: 'SUCCESS',
  },
  {
    id: 'log-002',
    timestamp: '2026-09-02 18:26:30',
    userEmail: 'carlos.rodriguez@gmail.com',
    userRole: 'family',
    action: 'ACCESS_DELEGATED_AGENDA',
    module: 'Agenda Médica',
    details: 'Familiar autorizado consultó las próximas citas médicas del paciente usr-001',
    ipAddress: '186.154.89.12',
    status: 'SUCCESS',
  },
  {
    id: 'log-003',
    timestamp: '2026-09-02 18:27:00',
    userEmail: 'maria.rodriguez@gmail.com',
    userRole: 'patient',
    action: 'MED_DOSE_RECORDED',
    module: 'Medicamentos',
    details: 'Registro de toma realizada: Enalapril 10 mg a las 08:05',
    ipAddress: '190.84.112.45',
    status: 'SUCCESS',
  },
  {
    id: 'log-004',
    timestamp: '2026-09-02 18:28:15',
    userEmail: 'admin.fet@guiasalud.edu.co',
    userRole: 'admin',
    action: 'VERIFIED_URL_UPDATED',
    module: 'Tutoriales y Contenidos',
    details: 'Actualización de enlace oficial verificado para trámites ADRES',
    ipAddress: '190.27.18.204',
    status: 'SUCCESS',
  },
  {
    id: 'log-005',
    timestamp: '2026-09-01 14:10:02',
    userEmail: 'maria.rodriguez@gmail.com',
    userRole: 'patient',
    action: 'CLINICAL_FILE_ENCRYPTED_ACCESS',
    module: 'Historia Clínica',
    details: 'Acceso seguro y descifrado en memoria de documento doc-001 (Hemograma)',
    ipAddress: '190.84.112.45',
    status: 'SUCCESS',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-001',
    title: 'Próxima cita médica',
    message: 'Tienes cita de Medicina General con el Dr. Andrés Morales el 4 de septiembre a las 09:30.',
    type: 'appointment',
    timestamp: 'Hace 1 hora',
    read: false,
    targetScreen: 'agenda',
  },
  {
    id: 'notif-002',
    title: 'Alerta de Medicamento: Omeprazol',
    message: 'Tu tratamiento de Omeprazol (14 días) está a 1 día de finalizar. Consulta con tu médico para renovar receta.',
    type: 'medication',
    timestamp: 'Hace 3 horas',
    read: false,
    targetScreen: 'medications',
  },
  {
    id: 'notif-003',
    title: 'Aviso de Seguridad 2FA',
    message: 'Se registró un inicio de sesión seguro verificado mediante Doble Factor de Autenticación.',
    type: 'security',
    timestamp: 'Ayer',
    read: true,
    targetScreen: 'profile',
  },
];
